name: Currents End-to-end tests

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      project-id:
        required: true
        type: string
      env-url:
        required: true
        type: string
    secrets:
      CURRENTS_RECORD_KEY:
        required: true

jobs:
  cypress-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # see https://currents.dev/readme/ci-setup/github-actions#how-to-setup-git-commit-data-for-cypress-when-using-github-actions
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install
        run: yarn
      # Install Currents
      - name: Install currents
        run: yarn add @currents/cli
      # Run all Cypress tests
      - name: Run Cypress test on Currents.dev
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.config.ts
          browser: chrome
          config: baseUrl=${{ inputs.env-url }},projectId=${{ inputs.project-id }}
          command: yarn currents run --record --parallel --key ${{ secrets.CURRENTS_RECORD_KEY }} --ci-build-id "${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}} --browser chrome"
