name: Continuous integration

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install
        run: yarn

      - name: Code style
        run: yarn lint

      - name: UI E2E Tests
        uses: cypress-io/github-action@v4
        with:
          config-file: cypress.config.ts
          install-command: yarn --immutable
          browser: chrome
          headless: true
          record: true
          parallel: true
          group: 'Actions example'
          env: CONTAINER=container
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
          COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}
          #  # pass the Dashboard record key as an environment variable
          # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # # pass GitHub token to allow accurately detecting a build vs a re-run build
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # # pass the project ID from the secrets through environment variable
          # CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
